### ISSUE TITLE
Appraisal

### ISSUE THREAD

**Issue by FrancoSpeziali** [AndrejsGrocs/backend-banking-asset-management-database#2]
# Appraisal

## Overall

- Great README file. Most people forget to do this
- Great folder structuring and overall use of the principles you learned during the module

I don't know enough about this industry to comment on the specifics of the models, but overall I don't think I can fault it in anyway.

Perhaps the only thing I would add is, have you looked into adding some validation for some of the fields?

Aside from that, very well done. I'm very impressed

**Comment by AndrejsGrocs** [comment]
Hi Franco. Thank you for the review. Actually, I need to finish this project a little, not all elements are showing as I would like to see. And if we will have enough time this structure will be nested into our final project banking application. Also, I would like to use this finished project as my portfolio.
